import type { FeedbackIssue, RoleFamily } from "./types";

type IssueLibrary = Record<
  FeedbackIssue,
  {
    mild: string[];
    moderate: string[];
    high: string[];
  }
>;

type RoleNarrativeLibrary = Record<
  RoleFamily,
  {
    praise: string[];
    alignment: string[];
    mismatch: string[];
  }
>;

export const ISSUE_LIBRARY: IssueLibrary = {
  weak_closing: {
    mild: [
      "Your ending is close, but it needs one clearer takeaway sentence.",
      "The final line is serviceable, but it does not land as strongly as it could.",
      "You are getting to the finish line - now make the outcome more explicit.",
      "The answer ends cleanly enough, but the takeaway is still a little soft.",
      "Your close is understandable, though it could be more memorable.",
      "The final sentence works, but it is not doing enough to elevate the answer.",
      "You are almost closing the loop, but the result needs slightly more emphasis.",
      "The answer has a finish, but not yet a strong payoff.",
      "The ending is decent, though it could leave a clearer impression.",
      "A more explicit final takeaway would make this answer feel more complete.",
      "The close is not weak, but it is not yet sharp enough to stand out.",
      "You reach the end of the story, but the impact lands a bit lightly.",
      "The final thought is present, though it needs more force.",
      "The answer resolves, but the result is still not fully highlighted.",
      "Your ending would be stronger with one sentence that states what changed.",
      "The close is structurally fine, but not yet fully persuasive.",
      "The answer would benefit from a more decisive final line.",
      "You have the ingredients for a good ending, but the payoff is still understated.",
      "The finish is clear enough, though not yet strong enough to be memorable.",
      "A stronger result sentence would make this feel much more complete.",
    ],
    moderate: [
      "You explain what you did, but the answer loses force because the result is not fully stated.",
      "The biggest scoring leak is at the finish line - the answer needs a sharper outcome statement.",
      "Your answer builds reasonably well, then stops before the payoff is fully clear.",
      "The close is softer than the rest of the answer and costs you impact.",
      "The story is mostly there, but the final result does not land strongly enough.",
      "You are explaining the action more clearly than the outcome, and that weakens the finish.",
      "The answer has momentum until the end, where the result becomes too vague.",
      "The closing thought is present, but not clear enough to carry the story.",
      "This answer would score higher with a stronger final impact sentence.",
      "You have useful content, but the end does not convert it into a clear outcome.",
      "The answer stops too close to the action and not close enough to the result.",
      "The finish is costing points because it sounds more implied than stated.",
      "The outcome is there in spirit, but not yet in a crisp enough sentence.",
      "The final section is underselling the story you just told.",
      "You are very close to a stronger answer, but the ending does not fully cash it in.",
      "The conclusion feels incomplete because the interviewer still has to infer the payoff.",
      "The answer needs a more explicit outcome to feel finished and convincing.",
      "The closing line is too light relative to the rest of the story.",
      "This answer does not fully stick the landing because the result stays too broad.",
      "The biggest gain here would come from a clearer and more memorable final outcome.",
    ],
    high: [
      "Too many points are being lost at the end because the answer stops after the action instead of clearly stating the result.",
      "The answer does not truly close - it trails off before the business impact becomes clear.",
      "Your final sentence is not doing enough work. Right now the interviewer has to infer the outcome.",
      "The story has effort, but the impact is buried or missing at the end.",
      "This answer finishes before the payoff becomes clear.",
      "A major weakness is that the answer never fully states what changed because of your action.",
      "The close is weak enough that it drags down the whole answer.",
      "Right now the ending sounds unfinished instead of intentional.",
      "The answer gives the setup and action, but fails to fully deliver the result.",
      "You are losing important points because the payoff never lands cleanly.",
      "The ending is underdeveloped enough that the interviewer is left doing the final interpretation.",
      "The result is too vague or too absent for the answer to score like a strong response.",
      "This answer needs a real finish, not just a stopping point.",
      "The final outcome is unclear enough that it weakens the whole story.",
      "The answer is missing the sentence that proves why the story matters.",
      "The close does not convert your effort into a convincing business or team outcome.",
      "The ending is the main point of failure here - it does not clearly state the impact.",
      "You are stopping the story before the strongest sentence is actually spoken.",
      "The answer feels incomplete because the outcome is not properly articulated.",
      "The biggest fix is a real result line that tells the interviewer what happened because of your work.",
    ],
  },

  low_specificity: {
    mild: [
      "The answer would feel stronger with one more concrete detail.",
      "A small amount of additional specificity would make the example more credible.",
      "You are close to convincing detail, but one sharper fact or number would help.",
      "The answer is understandable, but slightly more precision would improve it.",
      "One specific detail would make the story feel more real.",
      "The answer works, though it could use one clearer example or fact.",
      "You have enough context, but not quite enough precision.",
      "The story would become more memorable with one sharper detail.",
      "A little more factual texture would improve credibility.",
      "This answer is close - it just needs one more specific anchor point.",
      "You have the outline, but a concrete example would strengthen it.",
      "A single clearer detail would help the interviewer trust the example faster.",
      "The response makes sense, but could be made more tangible.",
      "You are near the right level of detail, but not fully there.",
      "The answer would benefit from one more precise action or decision point.",
      "There is enough to follow, but not enough to fully picture the situation.",
      "One concrete number, constraint, or decision would add weight here.",
      "You have relevance, but a little more specificity would make it more persuasive.",
      "A sharper example detail would improve how grounded this sounds.",
      "This would feel stronger if one part of the story were made more concrete.",
    ],
    moderate: [
      "The answer sounds generally capable, but it relies on broad language more than concrete detail.",
      "You describe the situation at a reasonable level, but the example still feels a bit generalized.",
      "There is enough structure here, but not enough precision to make the story fully memorable.",
      "The answer would benefit from one specific decision, number, or tradeoff.",
      "The story is directionally strong, but too broad in the details that matter most.",
      "You explain the shape of the situation, but not enough of the specifics inside it.",
      "The answer feels more summarized than experienced.",
      "This example is relevant, but not as concrete as it needs to be.",
      "You are describing the story clearly, but not proving it concretely enough.",
      "The answer would be more convincing with more exact detail on what you actually did.",
      "The content sounds plausible, but still too generalized to feel standout.",
      "You are close to a strong example, but broad phrasing is weakening it.",
      "This story needs more proof and less summary.",
      "The detail level is serviceable, though not strong enough to differentiate you.",
      "The interviewer gets the point, but not enough specifics to fully trust the example.",
      "The answer feels polished, but a little too abstract.",
      "You are saying the right kinds of things, but not with enough concrete support.",
      "More exact language around the decision, metric, or tradeoff would help.",
      "The story is not empty, but it is not yet specific enough to feel compelling.",
      "The answer would be stronger if it named one or two sharper details instead of staying broad.",
    ],
    high: [
      "The main weakness is specificity - the answer sounds plausible, but not grounded enough in what actually happened.",
      "Right now the interviewer gets the theme of the story, but not enough detail to trust the example.",
      "The answer leans too heavily on general language and not enough on concrete proof.",
      "You need more specific facts, actions, or outcomes to make the story believable and strong.",
      "The example is too abstract to create a strong signal.",
      "The story sounds real in outline, but not yet in evidence.",
      "You are describing competence more than demonstrating it.",
      "The answer is missing the concrete proof points that make examples credible.",
      "This feels more like a summary of experience than a real story with texture.",
      "The lack of specificity is strong enough to weaken the whole answer.",
      "The interviewer would struggle to visualize what actually happened here.",
      "The story needs concrete detail to move from plausible to convincing.",
      "Too much of the answer stays generic instead of grounded.",
      "There is not enough factual precision for this to score like a strong example.",
      "The answer sounds broad where it should sound exact.",
      "The content is too generalized to fully establish credibility.",
      "This story needs sharper details on what happened, what you did, and what changed.",
      "The answer is not failing on relevance - it is failing on proof.",
      "You are talking around the example more than fully showing it.",
      "Without more concrete detail, this answer will continue to sound thinner than it should.",
    ],
  },

  weak_ownership: {
    mild: [
      "Your ownership is present, but it could be stated more directly.",
      "You hint at your role, but it would help to make your contribution slightly clearer.",
      "The answer would gain authority if you named your role more explicitly.",
      "Your contribution is there, but it does not stand out enough yet.",
      "The story would be stronger if your role were more directly named.",
      "You are involved in the example, though not quite clearly enough.",
      "Your ownership is visible, but still understated.",
      "The answer would sound more confident if your role were sharper.",
      "Your contribution is implied more than stated.",
      "The story works, but your personal impact could be clearer.",
      "There is ownership here, though it could be more explicit.",
      "The answer would gain credibility if you claimed your role more directly.",
      "Your role is present, but slightly too soft.",
      "You are part of the story, but your personal contribution needs more shape.",
      "The answer would benefit from stronger first-person ownership language.",
      "Your involvement is clear enough, though not memorable enough.",
      "The story is collaborative, but your specific responsibility needs more emphasis.",
      "A more direct statement of your role would strengthen this answer.",
      "You have ownership, but you are not fully signaling it yet.",
      "Your contribution is visible, though not highlighted enough.",
    ],
    moderate: [
      "The answer sounds collaborative, but your personal ownership is still softer than it should be.",
      "You describe the work well enough, but the interviewer should not have to guess which part was yours.",
      "Your role is visible, but not emphasized enough to strengthen the answer.",
      "You need stronger first-person ownership language to make the example feel more credible.",
      "The answer explains the work, but not your exact contribution strongly enough.",
      "The story becomes less persuasive because your role blends into the group too much.",
      "You are describing good work, though not clearly enough as your work.",
      "This answer needs stronger ownership to feel more interview-ready.",
      "The example has value, but your role is still too soft in the telling.",
      "The interviewer should leave knowing exactly what you drove here.",
      "You are under-claiming your contribution relative to the story’s value.",
      "The answer sounds competent, but your ownership signal is weaker than it should be.",
      "Right now the example feels somewhat collective instead of clearly yours.",
      "You need to speak more directly about the part you led, decided, or changed.",
      "The story would land better if your contribution were more explicit and more central.",
      "There is a gap between the work described and the ownership claimed.",
      "The answer is directionally good, but your personal agency is not clear enough.",
      "You sound involved, though not yet clearly accountable for the critical move.",
      "The example would feel stronger if your contribution were harder to miss.",
      "You need a firmer statement of ownership so the interviewer is not left inferring it.",
    ],
    high: [
      "A major weakness here is ownership - the answer talks about what happened, but not clearly enough about what you drove.",
      "The story becomes less convincing because your personal contribution stays too vague.",
      "The answer sounds like a team summary more than a strong example of your own judgment.",
      "You need to claim your decision-making more clearly instead of letting the example stay collective.",
      "The biggest issue is that your role in the outcome is still too unclear.",
      "This answer weakens itself by failing to clearly state what you personally led or changed.",
      "The interviewer should not have to reconstruct your ownership from context.",
      "Right now the story sounds shared, but not owned.",
      "The example is doing too much group talk and not enough individual accountability.",
      "The answer needs stronger first-person clarity to sound convincing.",
      "You are describing activity without clearly enough describing your agency.",
      "The story sounds like good work happened, but not clearly enough because of you.",
      "Ownership is vague enough here that it directly weakens credibility.",
      "The answer does not yet establish you as the driver of the key action.",
      "This story needs a much firmer statement of what you specifically did and decided.",
      "The example becomes less persuasive because your direct responsibility is blurred.",
      "The answer undercuts itself by keeping your contribution too collective.",
      "The biggest gain would come from claiming your role much more clearly.",
      "You need to name what you owned, changed, recommended, or led.",
      "Until ownership is clearer, this answer will continue to feel softer than it should.",
    ],
  },

  weak_structure: {
    mild: [
      "The answer is mostly followable, but the sequencing could be cleaner.",
      "Your structure is workable, though a slightly clearer order would improve flow.",
      "The answer has the right pieces, but not the cleanest shape.",
      "A little more signposting would make this easier to follow.",
      "The answer works, but could be organized more intentionally.",
      "Your flow is understandable, though not fully crisp.",
      "The structure is decent, but still a bit loose.",
      "You have the right components, but not the strongest order.",
      "A cleaner setup-to-action transition would help.",
      "The answer could be easier to follow with slightly sharper sequencing.",
      "Your flow is adequate, though not yet polished.",
      "The structure is present, but could be more deliberate.",
      "A more obvious progression would strengthen the answer.",
      "The story makes sense, but the order could be tighter.",
      "This is followable, though a cleaner structure would help it score higher.",
      "You are not far off structurally, but the answer could be shaped more cleanly.",
      "The answer would feel stronger with better signposting between sections.",
      "The sequence is mostly right, just not fully sharp.",
      "You have the material; it just needs slightly better organization.",
      "A little more structure discipline would improve clarity immediately.",
    ],
    moderate: [
      "The answer contains good material, but the structure makes the story feel less sharp than it could.",
      "Your flow drifts a little between setup, action, and result.",
      "The main point arrives later than it should, which weakens the overall impact.",
      "The answer needs clearer sequencing so the interviewer does not have to organize it for you.",
      "The content is usable, but the structure is costing you clarity.",
      "The story feels slightly loose even though the underlying material is decent.",
      "The answer has useful pieces, but they are not arranged in the strongest order.",
      "Your response would score better if it moved more cleanly from point to point.",
      "The logic of the answer is there, but the structure is not helping it enough.",
      "The answer feels more assembled than designed.",
      "You are saying relevant things, but not in the cleanest progression.",
      "The structure is making the answer feel weaker than the content actually is.",
      "There is too much drift between sections for this to feel fully controlled.",
      "The story would land better if it were built more intentionally.",
      "The answer does not yet feel disciplined in how it moves from setup to result.",
      "The flow weakens your strongest ideas because they arrive later than they should.",
      "This answer needs stronger organization to sound more polished and more confident.",
      "The sequencing is not chaotic, but it is not sharp enough either.",
      "Your structure needs more discipline to help the story carry weight.",
      "The answer would benefit from clearer signposts and a cleaner order of operations.",
    ],
    high: [
      "Structure is a real issue here - the answer moves, but not in a way that feels controlled.",
      "The example has content, but the sequencing is costing you clarity and confidence.",
      "The story feels assembled rather than intentionally built.",
      "The biggest improvement would come from giving this answer a cleaner beginning, middle, and end.",
      "The answer lacks enough structural control to feel interview-ready.",
      "Your ideas are present, but the organization is weak enough to obscure them.",
      "The response needs a stronger shape before the content can score fully.",
      "The structure is loose enough that it becomes a central weakness.",
      "Right now the answer depends too much on the interviewer to do the organizing.",
      "The story is not flowing with enough control to sound strong.",
      "This answer needs a more disciplined frame or it will continue to feel messy.",
      "The content is getting buried by a structure that does not support it well.",
      "The sequence of the story is weak enough to meaningfully hurt scoring.",
      "The interviewer should not have to work this hard to follow the answer.",
      "You have relevant points, but the answer lacks a clear and controlled progression.",
      "The structure is undermining the story rather than strengthening it.",
      "This answer needs a far clearer path from setup to action to result.",
      "The current flow makes the answer feel less confident and less polished than it could be.",
      "A major fix is simply reorganizing this into a more intentional answer shape.",
      "Until structure improves, even better content will struggle to fully land.",
    ],
  },

  rushed_delivery: {
    mild: [
      "Your pace is only slightly fast, but slowing down on key moments would help.",
      "The answer is understandable, though a few pauses would make it land better.",
      "You are speaking fast enough that some good points pass by too quickly.",
      "A small tempo adjustment would improve control.",
      "Your pace is just a little quick for the most important moments.",
      "The speed is not a major issue, but it is beginning to trim clarity.",
      "A few more pauses would make the delivery feel stronger.",
      "The answer moves quickly enough to reduce some emphasis.",
      "You are not fully rushing, but you are not giving key lines enough space.",
      "The pace is manageable, though a touch too fast to maximize impact.",
      "You would sound more controlled with slightly slower transitions.",
      "A little more pacing discipline would help the answer breathe.",
      "The delivery is energetic, though not fully settled.",
      "The answer would benefit from more pause around your strongest points.",
      "You are moving just quickly enough to soften emphasis.",
      "The content is fine, but the pace is not helping it as much as it could.",
      "The speed is workable, though a bit quick for high-stakes moments.",
      "Your points are arriving quickly enough to lose some weight.",
      "The tempo could be more intentional.",
      "A slightly slower pace would improve how polished this sounds.",
    ],
    moderate: [
      "The pace is fast enough to reduce clarity at the exact moments where you need emphasis.",
      "You sound energetic, but the answer would be stronger with more control around key points.",
      "Important points move by quickly instead of landing cleanly.",
      "You would gain polish by slowing down after metrics, decisions, and results.",
      "The speed is beginning to work against the answer’s strongest content.",
      "The pace makes the answer feel more hurried than confident.",
      "You are moving quickly enough that the answer loses some control.",
      "Fast delivery is softening the clarity of otherwise useful content.",
      "The answer feels more rushed than intentional.",
      "Your delivery would score better with a more controlled tempo.",
      "The speed is not constant, but it rises in the exact places where you need emphasis.",
      "Good ideas are not getting enough space to land.",
      "The pace is turning strong moments into quick mentions.",
      "The answer sounds capable, but not fully settled.",
      "You are moving fast enough to reduce polish and emphasis at the same time.",
      "The content would be easier to trust if it were delivered with more control.",
      "The answer needs a calmer rhythm around the most important lines.",
      "You are sacrificing landing power for speed.",
      "A strong improvement would come from letting key points breathe.",
      "The pace is quick enough to make the answer feel less controlled than it actually is.",
    ],
    high: [
      "The answer sounds rushed, which makes strong content feel less controlled than it actually is.",
      "You are moving quickly enough that clarity and emphasis both suffer.",
      "The delivery is pushing the answer forward before the important ideas can land.",
      "A major gain would come from slowing the tempo and letting the answer breathe.",
      "The pace is actively weakening the answer’s strongest content.",
      "The answer sounds hurried enough to affect both polish and confidence.",
      "You are outrunning your own best points.",
      "The delivery does not give key ideas enough time to register.",
      "This answer is being pulled forward by speed instead of controlled by intention.",
      "Rushed delivery is a major reason the answer feels less convincing.",
      "The pace is reducing the authority of what you are saying.",
      "The answer needs more control and less forward pressure.",
      "Your strongest lines are not getting enough space to matter.",
      "The delivery is moving too fast to sound fully polished or deliberate.",
      "The answer feels like it is trying to finish before it has fully landed.",
      "Speed is turning solid content into a less controlled performance.",
      "This is fast enough that it meaningfully hurts impact.",
      "A central problem here is that the answer never really settles.",
      "The pace is making the response feel less thoughtful than it actually is.",
      "The answer would improve immediately if the tempo became more deliberate.",
    ],
  },

  slow_delivery: {
    mild: [
      "The pace is a touch slow, though still manageable.",
      "You are understandable, but slightly tighter delivery would improve energy.",
      "A little less runway in the opening would help the answer feel stronger.",
      "You have enough clarity - now tighten the tempo slightly.",
    ],
    moderate: [
      "The answer is slower than ideal, which makes it feel more hesitant than it needs to.",
      "You give the setup too much time before the main point arrives.",
      "The pacing makes the answer feel heavier than the content really is.",
      "More concise early sentences would immediately improve momentum.",
    ],
    high: [
      "The answer feels overbuilt because the pace stays too slow for too long.",
      "Slow delivery is making the answer sound less decisive than the content deserves.",
      "You are taking too long to get to the point, which weakens confidence and clarity.",
      "The answer needs tighter first sentences and less verbal runway.",
    ],
  },

  flat_delivery: {
    mild: [
      "Your tone is stable, but a little more emphasis would improve memorability.",
      "The delivery is composed, though slightly more vocal lift would help key moments.",
      "Your tone is steady but could separate background from outcome more clearly.",
      "A little more emphasis on the result would strengthen delivery.",
    ],
    moderate: [
      "Your delivery stays relatively even, which makes strong moments sound less important than they are.",
      "The answer would benefit from more vocal contrast between setup and result.",
      "You sound controlled, but a bit too flat on the most important lines.",
      "The content is stronger than the vocal emphasis currently suggests.",
    ],
    high: [
      "Flat delivery is making the answer feel less engaging and less memorable than it should.",
      "You are not giving the key moment enough vocal contrast, so the outcome lands softly.",
      "Right now the tone treats all parts of the answer too similarly.",
      "The answer needs more vocal emphasis on decisions, outcomes, and takeaways.",
    ],
  },

  filler_overuse: {
    mild: [
      "Filler words are noticeable but still fixable with a little more pause control.",
      "The answer has some filler bleed, especially in transitions.",
      "You are using a few more fillers than ideal, though this is still manageable.",
      "A little more silence would improve polish immediately.",
      "Fillers are present, though not yet dominating the answer.",
      "You are relying on a few verbal placeholders between points.",
      "The answer would sound cleaner with slightly fewer fillers.",
      "This is not a major problem, but it is noticeable enough to address.",
      "A few pauses would sound better than some of the filler language here.",
      "The fillers are not overwhelming, but they are trimming polish.",
      "Some transitions are leaning on filler instead of silence.",
      "You have mild filler drift that is worth tightening.",
      "The answer is reasonably polished, though fillers are beginning to show.",
      "A cleaner pause strategy would improve this quickly.",
      "The filler usage is moderate enough to fix fast.",
      "The answer would sound sharper with fewer verbal placeholders.",
      "Your transitions would feel cleaner with less filler language.",
      "The fillers are not severe, but they are present enough to soften delivery.",
      "This answer would feel more intentional with cleaner pauses.",
      "You are close to polished delivery, but filler language is still slightly getting in the way.",
    ],
    moderate: [
      "Filler usage is starting to weaken polish and make the answer feel less controlled.",
      "You are relying on verbal placeholders in transitions instead of clean pauses.",
      "The content is reasonably solid, but filler words are softening delivery.",
      "A visible win would come from replacing filler with one-beat silence.",
      "The filler usage is noticeable enough to reduce confidence and polish.",
      "You are losing some composure in the transitions between points.",
      "The answer would sound stronger with cleaner verbal control.",
      "Filler words are becoming a distraction rather than just a habit.",
      "The content is not the issue - the delivery leakage is.",
      "You have enough substance here, but fillers are weakening how composed it sounds.",
      "The answer would feel more professional with fewer placeholder words.",
      "Fillers are making the transitions feel less controlled than they should.",
      "This is one of the clearer delivery leaks in the answer.",
      "The filler usage is beginning to shape perception of confidence.",
      "The response is good enough to deserve cleaner delivery than this.",
      "You are using fillers often enough that they now affect polish.",
      "The answer would immediately feel sharper with cleaner pauses.",
      "Filler language is softening the impact of otherwise useful content.",
      "This is a noticeable delivery issue, not just a background habit.",
      "A meaningful delivery improvement would come from reducing filler usage in transitions.",
    ],
    high: [
      "Filler words are significantly reducing polish and making the answer sound less composed.",
      "The main delivery leak here is filler overuse, especially when moving between points.",
      "Your answer would sound substantially stronger with cleaner pauses instead of placeholders.",
      "Filler usage is distracting enough to affect overall perception of confidence.",
      "The filler frequency is high enough that it becomes a central weakness.",
      "This answer sounds less controlled primarily because of filler overuse.",
      "The amount of placeholder language is clearly hurting polish.",
      "You are using enough fillers that the delivery no longer feels settled.",
      "This is more than occasional filler - it is shaping the tone of the answer.",
      "A major reason this answer sounds less polished is the heavy reliance on filler language.",
      "The fillers are pulling attention away from the actual content.",
      "The answer needs a cleaner pause strategy, not more words between points.",
      "Filler overuse is reducing both clarity and authority.",
      "This level of filler usage makes the answer sound less composed than the content deserves.",
      "The strongest immediate delivery gain is reducing filler words substantially.",
      "The answer is being undercut by how often verbal placeholders appear.",
      "Filler usage is now a front-and-center delivery problem.",
      "The answer would feel far more confident with cleaner silence and fewer placeholders.",
      "Right now the fillers are weakening both polish and credibility.",
      "This is one of the main reasons the answer feels less interview-ready than it could.",
    ],
  },

  weak_role_alignment: {
    mild: [
      "The answer is relevant, but the connection to the target role could be more explicit.",
      "You are not far off, but the role fit signal could be stronger.",
      "The answer would benefit from a clearer link to what this role actually values.",
      "There is some alignment, but it is not yet obvious enough.",
      "The story is relevant, though the fit to this role is still somewhat understated.",
      "You answer the question, but not yet in the strongest language for this role.",
      "The role connection is present, though not emphasized enough.",
      "This answer would benefit from one clearer line tying it to the role.",
      "You are close to sounding role-aligned, but not fully there.",
      "The example works, but it is not yet clearly framed around what this job rewards.",
      "The answer is directionally relevant, but the role-fit signal is still soft.",
      "A small reframing would make this sound much more role-specific.",
      "The content is usable, though not yet tailored enough to the role.",
      "You are showing useful experience, but not fully translating it to the job.",
      "The answer could more clearly signal why this story matters for the role.",
      "Relevance is there, but role relevance is still somewhat muted.",
      "The story fits, though the role alignment could be sharper.",
      "The answer would be stronger if it named the role-relevant takeaway more clearly.",
      "There is a fit signal here, but it needs more emphasis.",
      "The role connection is implied more than clearly stated.",
    ],
    moderate: [
      "The example is decent, but it does not yet sound tailored to what this role most rewards.",
      "You answer the question, but the role-specific relevance could be much clearer.",
      "The content works in general, though it is not framed strongly enough for this role.",
      "The answer needs a stronger connection to the job’s priorities and expectations.",
      "The story is fine, but it is not yet helping you look especially aligned to the role.",
      "The interviewer can see capability, but not enough specific fit.",
      "This answer sounds competent overall, though not clearly tuned to the job.",
      "The role match is weaker than the general answer quality.",
      "You are showing useful experience, but not yet framing it in the role’s language.",
      "This would land better if it sounded more intentionally tailored to the position.",
      "The example is relevant, but not yet strategically framed for this role.",
      "The answer needs a clearer bridge between your experience and the role’s priorities.",
      "You are answering the question, but missing some role-fit opportunity.",
      "The content is not off-base - it is just not role-specific enough.",
      "This answer needs more explicit translation into what the role values.",
      "The fit signal is weaker than it should be for a targeted answer.",
      "You are not yet turning the example into a clear role match.",
      "The story should do more to prove why you fit this specific role.",
      "The answer works broadly, but not strongly enough for this audience.",
      "A stronger role-specific frame would raise the impact of the same content.",
    ],
    high: [
      "A major weakness here is role alignment - the answer does not make a strong case for why you fit this specific role.",
      "The example sounds broadly competent, but not clearly tuned to the role you are targeting.",
      "You are missing the chance to show why this story matters in the context of this role.",
      "The answer needs to translate your experience into the language of the job more clearly.",
      "The interviewer hears a reasonable answer, but not yet a convincing fit signal.",
      "This answer is too general for a role-targeted response.",
      "The story may be real and relevant, but it is not being framed in a role-specific way.",
      "The fit gap is not ability alone - it is how weakly the answer maps to the role.",
      "The answer is missing the explicit connection between your story and this role’s priorities.",
      "You are not yet using the story to prove why you belong in this seat.",
      "The content is serviceable, but the role match is not yet persuasive.",
      "This answer needs a much stronger translation into the priorities of the job.",
      "The story sounds capable, but not sufficiently aligned to this specific role family.",
      "The fit signal is weak enough that it becomes a central issue.",
      "You need to show not just that you can do good work, but that you can do the kind of work this role values.",
      "The answer is too broad to function as strong role-fit evidence.",
      "A major improvement would come from connecting your example directly to the job’s priorities.",
      "Right now the story sounds like a generic good answer instead of a role-specific strong answer.",
      "The role connection is weak enough that it limits the answer’s value.",
      "Until alignment is clearer, this answer will continue to sound more general than targeted.",
    ],
  },

  shallow_technical: {
    mild: [
      "The explanation is understandable, but it could go one layer deeper.",
      "You have the outline of the logic, though more depth would improve credibility.",
      "The answer is directionally right, but not quite deep enough yet.",
      "A little more technical detail would strengthen the explanation.",
    ],
    moderate: [
      "The explanation is structured, but still feels somewhat shallow for a strong technical answer.",
      "You describe the idea, though not enough of the reasoning behind it.",
      "The answer would be stronger with more explicit tradeoffs, steps, or technical constraints.",
      "The current level of detail is serviceable, but not differentiating.",
    ],
    high: [
      "The biggest weakness is technical depth - the answer sounds broad rather than grounded in real reasoning.",
      "You are using the shape of a technical answer without enough technical substance inside it.",
      "The explanation needs more real detail, tradeoff logic, or process specificity.",
      "This answer feels too high-level to score like a strong technical explanation.",
    ],
  },

  thin_experience_depth: {
    mild: [
      "The example is relevant, though it could show more depth.",
      "You point to real experience, but the richness of the example is still limited.",
      "There is enough here to work with, though it could be developed further.",
      "The answer would benefit from a little more depth and specificity.",
    ],
    moderate: [
      "The experience is relevant, but the example still feels thinner than it should.",
      "You mention useful experience, though not at enough depth to fully differentiate yourself.",
      "The answer would be stronger with more concrete detail on tools, decisions, or impact.",
      "The example is credible, but not yet rich enough to feel standout.",
    ],
    high: [
      "The answer references experience, but not with enough depth to create a strong signal.",
      "You need a fuller example so the interviewer can actually see the work and your role in it.",
      "The experience exists, but the answer is not unpacking it deeply enough.",
      "This feels more like a summary of experience than a strong demonstration of it.",
    ],
  },

  partial_answer: {
    mild: [
      "You answered most of the question, but one part could be addressed more directly.",
      "The core answer is there, though one piece of the prompt needs more attention.",
      "This is mostly relevant, but not fully complete.",
      "You are close - the answer just needs to cover the full question more explicitly.",
    ],
    moderate: [
      "The answer addresses the main theme, but leaves part of the question underdeveloped.",
      "You are relevant overall, though the response is not fully complete.",
      "One piece of the interviewer’s ask is still only partially addressed.",
      "The answer would score better if it closed the loop on the full prompt.",
    ],
    high: [
      "A major issue is completeness - the answer only addresses part of what the interviewer asked.",
      "You are speaking to the topic, but not fully answering the question.",
      "The response misses part of the prompt strongly enough to affect scoring.",
      "This answer needs to be more complete, not just more polished.",
    ],
  },

  overlong_setup: {
    mild: [
      "The setup is a little longer than it needs to be.",
      "You spend slightly too much time on context before the main point arrives.",
      "The opening is serviceable, though it could get to the answer faster.",
      "A shorter setup would sharpen the answer immediately.",
    ],
    moderate: [
      "Too much time is spent building context before the important part of the answer begins.",
      "The setup is eating into the strongest part of your answer.",
      "You are not losing the interviewer, but the runway is longer than necessary.",
      "The answer would feel sharper if you arrived at the action or conclusion faster.",
    ],
    high: [
      "The answer gives the setup too much airtime, which delays the real point.",
      "You are spending too long getting into the story, and it weakens momentum.",
      "The opening section is absorbing too much of the answer’s value.",
      "A major gain would come from cutting the setup and getting to the key move sooner.",
    ],
  },
};

export const ROLE_LIBRARY: RoleNarrativeLibrary = {
  finance: {
    praise: [
      "You sound strongest when you make the business takeaway easy to follow.",
      "Your better moments come when the answer feels concise, commercially aware, and outcome-driven.",
      "This role rewards clean communication and strong result framing, and you show flashes of both.",
      "Your strongest finance-style answers are the ones that sound commercially sharp and clearly structured.",
      "You are strongest when your answer sounds both analytical and decision-oriented.",
      "The answer works best for finance-heavy roles when you make the implication of the analysis obvious.",
      "A stronger finance signal appears when you sound concise and metric-aware.",
      "Your better responses are the ones that make the recommendation easy to follow.",
    ],
    alignment: [
      "For finance-oriented roles, sharper metric language usually raises credibility fast.",
      "Finance-heavy roles tend to reward concise logic and explicit business impact.",
      "A stronger finance signal usually comes from clearer metrics, tradeoffs, and recommendation framing.",
      "This role rewards answers that sound commercially aware, structured, and outcome-led.",
      "For this role family, stronger business framing usually improves perceived fit quickly.",
      "Finance roles respond well to concise analysis and clear recommendation logic.",
      "The more clearly you connect the story to business impact, the stronger the finance fit becomes.",
      "This role family usually rewards sharper outcomes and more explicit decision relevance.",
    ],
    mismatch: [
      "Right now the answer sounds capable, but not as commercially sharp as it should for a finance-heavy role.",
      "The main missing signal for this role is stronger outcome framing and more concrete decision impact.",
      "This role needs clearer evidence of business impact than the answer currently provides.",
      "The answer is relevant, but not yet framed with the level of commercial sharpness this role rewards.",
      "You sound generally capable, though not yet fully finance-aligned in how you present the impact.",
      "The story works, but the business payoff needs to be more explicit for this role family.",
      "This answer would feel more finance-ready with sharper metric language and stronger result framing.",
      "The role fit is being limited by how softly the business value is being expressed.",
    ],
  },

  operations: {
    praise: [
      "You are strongest when you sound structured under pressure and clear about tradeoffs.",
      "This role rewards prioritization, execution logic, and clarity under constraints.",
      "Your best operational answers are the ones that feel practical and decision-oriented.",
      "You sound most operations-ready when the answer focuses on prioritization and execution.",
      "This role family responds well when you sound concrete, practical, and structured.",
      "Your stronger moments come when you clearly explain how you sorted competing priorities.",
      "Operations-oriented answers feel strongest when you sound calm, practical, and execution-focused.",
      "You are strongest when the story highlights action under constraints.",
    ],
    alignment: [
      "Operations-oriented roles usually reward clear prioritization and explicit tradeoff reasoning.",
      "For this role, practical structure matters almost as much as polish.",
      "A strong operations signal comes from showing how you diagnose, prioritize, and execute.",
      "This role family rewards answers that make constraints and tradeoffs visible.",
      "Operations roles tend to value structured decision-making under ambiguity.",
      "The clearer your prioritization logic, the stronger the fit for this type of role.",
      "This audience wants to hear how you think when several variables are moving at once.",
      "For operations-heavy roles, execution logic usually matters more than broad storytelling polish.",
    ],
    mismatch: [
      "The answer needs more operational specificity and clearer tradeoff logic for this role.",
      "This role requires stronger prioritization and constraint-based reasoning than the answer currently shows.",
      "You sound capable, but not yet sharply operational in the way this role rewards.",
      "The example is useful, though not yet framed strongly enough around prioritization and execution.",
      "The answer would sound more role-aligned if it made the operational tradeoffs more visible.",
      "The fit gap here is less about relevance and more about practical decision logic.",
      "This story needs a clearer operations lens to feel fully aligned.",
      "The answer is not yet surfacing the execution and prioritization signal this role values most.",
    ],
  },

  research: {
    praise: [
      "You are strongest when you sound methodical, specific, and credible about process.",
      "This role rewards repeatability, clarity, and depth of example more than speed.",
      "Your better research-style answers are the ones that sound disciplined and evidence-based.",
      "You sound most research-aligned when the answer emphasizes process integrity and specificity.",
      "This role family rewards answers that feel careful, credible, and grounded in real method.",
      "Your strongest moments come when you sound systematic rather than broad.",
      "Research-oriented roles respond well when the story shows process discipline and repeatability.",
      "You are strongest when the example sounds concrete, careful, and evidence-aware.",
    ],
    alignment: [
      "Research-oriented roles reward process clarity, specificity, and credible ownership of the method.",
      "This role needs concrete example depth and clear explanation of how the work was stabilized or improved.",
      "A strong research signal comes from specificity, repeatability, and careful reasoning.",
      "For research-heavy roles, stronger fit usually comes from deeper process explanation and clearer methodology.",
      "This audience tends to reward discipline, detail, and credible workflow reasoning.",
      "The more repeatable and specific the story sounds, the stronger the research fit becomes.",
      "This role family wants method, not just summary.",
      "Research roles often value clarity of process more than speed of delivery.",
    ],
    mismatch: [
      "The answer needs more process depth and more explicit methodological ownership for this role.",
      "Right now the example is relevant, but not as deeply developed as a strong research answer should be.",
      "This role needs more specificity and less high-level summary than the current answer provides.",
      "The fit is being limited by a lack of process depth, not just by delivery.",
      "The answer would sound more research-ready with more method detail and clearer ownership of the workflow.",
      "The story is relevant, though still not developed enough for a research-heavy audience.",
      "This role family needs more concrete workflow or process detail than the current answer shows.",
      "The example is on theme, but not yet at the right depth for strong research alignment.",
    ],
  },

  consulting: {
    praise: [
      "You sound strongest when the answer is crisp, structured, and recommendation-led.",
      "This role rewards clarity, confidence, and clean synthesis.",
      "Your best moments are the ones where you sound decisive and well-framed.",
      "Consulting-style roles respond well when you lead with the answer and support it efficiently.",
    ],
    alignment: [
      "Consulting-style roles reward concise structure, ownership, and recommendation clarity.",
      "A stronger fit here usually comes from sharper synthesis and tighter control of the story.",
      "This role tends to reward clear framing, strong ownership, and polished delivery.",
      "For consulting-oriented roles, cleaner synthesis often matters as much as the raw example itself.",
    ],
    mismatch: [
      "The answer is not yet sharp enough for a consulting-style audience.",
      "This role would reward cleaner synthesis and a more decisive finish than the current answer provides.",
      "You need stronger ownership and recommendation framing for this role family.",
      "The fit gap here is mostly about sharpness, control, and synthesis.",
    ],
  },

  general: {
    praise: [
      "Your strongest moments come when the answer feels clear, direct, and intentionally structured.",
      "The answer works best when it balances clarity, ownership, and relevance.",
      "A generally strong answer here comes from clear structure and specific proof.",
      "You sound strongest when the story is simple, direct, and concrete.",
    ],
    alignment: [
      "Most roles reward a mix of structure, ownership, and concrete impact.",
      "A stronger overall fit usually comes from better specificity and cleaner closing.",
      "The broadest scoring gains usually come from making the answer clearer and more concrete.",
      "Most interviewers respond well when the answer is easy to follow and easy to trust.",
    ],
    mismatch: [
      "The answer needs stronger specificity and structure to feel more convincing overall.",
      "You sound directionally relevant, but not yet as concrete or controlled as the role would reward.",
      "The main gap is not relevance alone - it is clarity, specificity, and finish.",
      "This answer would feel stronger in almost any setting with clearer proof and a cleaner ending.",
    ],
  },
};
